name: build openwrt (Image Builder)

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: system setup
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          path: main

      - uses: actions/checkout@v6
        with:
          repository: ikas-mc/openwrt-config
          ref: 'main'
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
          path: openwrt-config
      
      - name: build
        run: |
          cp main/build-image.sh ./build.sh
          chmod +x ./build.sh
          ./build.sh amd64
          
      - name: upload openwrt-image
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-image-bin
          include-hidden-files: true
          retention-days: 7
          path: |
            openwrt-image/bin/targets/*/*combined-efi.img.gz
            openwrt-image/bin/targets/*/*kernel.bin
            openwrt-image/bin/targets/*/*rootfs.tar.gz
            openwrt-image/bin/targets/*/sha256sums
