name: build openwrt

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: system setup
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: free disk
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          path: main

      - uses: actions/checkout@v6
        with:
          repository: ikas-mc/openwrt
          ref: 'dev-040-md'
          fetch-depth: 1
          path: openwrt

      - uses: actions/checkout@v6
        with:
          repository: ikas-mc/openwrt-config
          ref: 'main'
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
          path: openwrt-config
      
      - name: build
        run: |
          cp main/build.sh ./build.sh
          chmod +x ./build.sh
          ./build.sh xg-040g-md
          
      - name: upload openwrt
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-bin
          include-hidden-files: true
          retention-days: 7
          path: |
            openwrt/bin
