name: build openwrt package

on:
  workflow_dispatch:
    inputs:
      deviceId:
        description: 'device id'
        required: true
        default: 'amd64'
        type: choice
        options:
        - "amd64"
        - "xg-040g-md"
      enableDebug:
        description: 'enable debug log'
        required: false
        default: false
        type: boolean
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: system setup
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          path: main

      - uses: actions/checkout@v6
        with:
          repository: ikas-mc/openwrt-config
          ref: 'main'
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
          path: openwrt-config
      
      - name: build
        run: |
          cp main/build-package.sh ./build.sh
          chmod +x ./build.sh
          ./build.sh ${{ github.event.inputs.deviceId }}
          
      - name: upload openwrt-packages
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-packages
          include-hidden-files: true
          retention-days: 7
          path: |
            openwrt-sdk/bin/packages/
